const CHARACTER_LIST_FAIL = "CHARACTER_LIST_FAIL";
const CHARACTER_LIST_SUCCESS = "CHARACTER_LIST_SUCCESS";
const CHARACTER_LIST_REQUEST = "CHARACTER_LIST_REQUEST";

export { CHARACTER_LIST_FAIL, CHARACTER_LIST_REQUEST, CHARACTER_LIST_SUCCESS };
